Traceback (most recent call last):
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 673, in merge_with
    new_dims.append(dim.merge_with(other[i]))
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 143, in merge_with
    self.assert_is_compatible_with(other)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 116, in assert_is_compatible_with
    other))
ValueError: Dimensions 5 and 1 are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 727, in _GradientsHelper
    in_grad.set_shape(t_in.get_shape())
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 511, in set_shape
    self._shape_val = self.shape.merge_with(shape)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 676, in merge_with
    raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (5, 5) and (1, 2) are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mae_test.py", line 18, in <module>
    train = optimizer.minimize(cost)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 399, in minimize
    grad_loss=grad_loss)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 511, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 532, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 734, in _GradientsHelper
    (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: MatMulAdditionError.  Input index: 0. Original input shape: (1, 2).  Calculated input gradient shape: (5, 5)